baseURL: "https://reggiani.io"
languageCode: en-us
title: Edo Reggiani
theme: "personal" #, "hugo-shortcode-gallery"]
copyright: "Â© Edo Reggiani"

paginate: 5
googleAnalytics: G-10ZPWLWNXR

params:
  mode: toggle
  header: Edo Reggiani
  author: Edo
  email: "**e.reggiani**[at]**protonmail**[dot]**com**"
  images:
    - img/main_img.png
  favicon:
    - name: base
      url: img/favicon.ico
    - name: apple
      url: img/apple-touch-icon.png
    - name: 32
      url: img/favicon-32x32.png
    - name: 16
      url: img/favicon-16x16.png
  social:
    - name: LinkedIn
      url: https://linkedin.com/in/edoardo-reggiani/
      weight: 1
    - name: X
      url: https://twitter.com/EdoardoReggiani
      weight: 2
    - name: Github
      url: https://github.com/regedo00
      weight: 3
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Blog"
      url: "/blogs/"
      weight: 3
    - name: "Stuff"
      url: "/stuff/"
      weight: 4
